- name: Adicionando a instancia criada no arquivo hosts
  local_action: lineinfile
    dest="./hosts"
    regexp={{ item.public_ip }}
    insertafter="[maquinasGIL]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"
