---
- name: 
  import_tasks: func/security_group.yml

- name: 
  import_tasks: func/instancia_ec2.yml

- name: 
  import_tasks: func/inventario.yml

- name: 
  import_tasks: func/arquivo_host.yml

- name: 
  import_tasks: func/ssh.yml

- name: 
  import_tasks: func/tag.yml

- name: 
  import_tasks: func/known_hosts.yml  
